---
# vars file for docker
user: yuchen
removedep:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  - docker.io
  - containerd
  - runc
packagesdep:
  - git
  - ca-certificates
  - wget
  - gnupg2
  - curl
dockerengine:
  - docker-ce
  - docker-ce-cli
  - containerd.io
