---
  - name: Install basic tools
    become: true
    become_method: su
    yum:
      name: "{{ tools }}"
      state: latest

  - name: Add wheel to user groups
    become: true
    user:
      name: '{{ user }}'
      groups: wheel
      append: yes