---
  - name: Install yum utils
    become: yes
    become_method: su
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  - name: Remove old docker packages
    become: yes
    yum:
      name: "{{ removedep }}"
      state: absent
  - name: Add Docker repo
    become: yes
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
  - name: Install packages for yum
    become: yes
    yum:
      name: "{{ packagesdep }}"
      state: latest
  - name: Actually install docker
    become: yes
    yum:
      name: "{{ dockerengine }}"
      state: latest
  - name: Add docker to user groups
    become: yes
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  - name: " Starting and Enabling Docker service"
    become: yes
    service:
      name: docker
      state: started
      enabled: yes